lynxlib:
    application:
        system-id: SYS000000000000
    datasource:
        - datasource-name: system-datasource #수정불가 Uncorrectable
          database-type: sqlserver #oracle sqlserver jtds db2 postgresql mysql mariadb tibero sqlite
          database-name: database-name
          server: 127.0.0.1
          port: 1234
          username: username
          password: password
          #jdbc-url-options: ;encrypt=true;trustServerCertificate=true #jdbc-url에 추가로 설정할 옵션이 있는경우 설정(예제는 sqlserver TLS 인증서 무시를 위한 설정)                 
    #rest-api:
    #    restTemplates:  #Rest API 호출 시 Proxy 설정. Proxy configuration for calling Rest API
    #        proxyHost: 192.168.0.1
    #        proxyPort: 8080
    #        proxyScheme: https               
    #        nonProxyHosts: www.abc.com #localhost, 127.0.0.1은 기본으로 설정 됨. localhost, 127.0.0.1 are set as default.  