lynxlib:
    rest-api: 
        credentials:
            portal:
                realm: ENC(DHH9QKfUWaArEI47ir8kGInQpbT9QfenxmupCVEYKlo=) #portal-client-id
                token: ENC(4AqgUOECg08Q8DFZxUz4K18TSl5tD1u5vwQkdH4bCRIdUGgsOGGRIFvco8M0tsSQB1XjLdR4esOSbcZkIyfJPQ==) #portal-client-secret
                endpoints: /long/oauth2/token
                scope: default_scope
                contentType: application/x-www-form-urlencoded
                httpMethod: POST
                grantType: password
                authorizationType: Basic
                username: ENC(PD0MQ7Nm19DQnYeENVVTCdD4rWlLn3YeUoUvClNZy9c=)
                password: ENC(oh7D0lMZy0ZUtl//42atyMNLjyurzpRw87TwPUW2BRSIzGC/UVxvjDsfDiVV51urb5z9l6e1Uso87c6JVemmSg==)
                clientId: ENC(k5lhJO7+dOiM5w6FA7JtiIcxoCmhPVvEOS4rhYPuIUCTMFVBkCPNjkczVUfBzWmDp7dodd9M6AShnFOBB27VYw==)
                clientSecret: ENC(ZnEa9E5n8G0G3MVw7HdvpDCLXtOtZAAfLgVGMhkTxFMIyaGgviQddLi/zO/txhb9MI5Wwsp3rusWtTKvr0+LXA==)
        baseUrls:
            portal: "https://scadev.ipaas.samsung.com/sec/kr"