lynxlib:
    rest-api: 
        credentials:
            portal:
                realm: ENC(DHH9QKfUWaArEI47ir8kGInQpbT9QfenxmupCVEYKlo=) #portal-client-id
                token: ENC(4AqgUOECg08Q8DFZxUz4K18TSl5tD1u5vwQkdH4bCRIdUGgsOGGRIFvco8M0tsSQB1XjLdR4esOSbcZkIyfJPQ==) #portal-client-secret
                endpoints: /long/oauth2/token
                scope: default_scope
                contentType: application/x-www-form-urlencoded
                httpMethod: POST
                grantType: password
                authorizationType: Basic
                username: ENC(PD0MQ7Nm19DQnYeENVVTCdD4rWlLn3YeUoUvClNZy9c=)
                password: ENC(uyftXUQtpMD2D785uOJPmyZ/uLLaRYABDLGLLnC3IzgR/D2fBAmyRbOJYF4YjAIPWKzyInvrd5HOK6tTtKolJQ==)
                clientId: ENC(M3od2bank6sOX+L9vdWT9HGTJAkI0+zqOBYP5sHV/AoRzCinj+//TqP48kZf1o6NnoJrvWp39MxJgTOtNVYV1A==)
                clientSecret: ENC(WFdBh+6s6nL49hTM4Sd1MGkJgLFXLtjfXDzaLLo/a/PlW9aZOGivGkQ2DtvxGtVC0PaW+1l6GUgiZsvv7Qx4qg==)
        baseUrls:
            portal: "https://sca.ipaas.samsung.com/sec/kr"